http_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :cats, only: [:index] => get '/cats' do 'Cat#index'
  resources :cats, only: [:index, :show, :edit, :update, :delete, :create, :new]
end

http_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

http_cats/app/models/cat.rb
class Cat < ApplicationRecord
    validates :sex, inclusion: { in: ["M", "F"] }
    has_many :cat_rental_requests, dependent: :destroy
end

http_cats/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
    validate :valid_request?
    belongs_to :cat

    has_many :other_requests,
        through: :cat,
        source: :cat_rental_request

    def valid_request?
        overlapping_requests.empty?
    end

    def overlapping_requests
        result_1 = other_requests.where(other_requests: {start_date: (self.start_date..self.end_date) })
        result_2 = other_requests.where(other_requests: {end_date: (self.start_date..self.end_date) })
        return result_1 + result_2
    end
end

http_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

http_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index #all records in the table AKA ActiveRecord#all
        @cats = Cat.all
        render :index
    end

    def show #individual record from table based on id AKA ActiveRecord#find(:id)
        @cat = Cat.find(params[:id])
        render :show
    end
    
    def edit
        @cat = Cat.find(params[:id])
        render :edit
    end

    def update
        @cat = Cat.find(params[:id])

        if @cat.update(cat_params)
            redirect_to cat_url(@cat)
        else
            render json: @cat.errors.full_messages, status: 422
        end
    end

    def new
        @cat = Cat.new
        render :new
    end

    def create
        @cat = Cat.new(cat_params)
        
        if @cat.save
            redirect_to cat_url(@cat)
        else
            render json: @cat.errors.full_messages, status: 422
        end
    end

    private

    def cat_params
        params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
    end
end

http_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

http_cats/app/views/cats/_form.html.erb
<% if edit %>
    <% bollocks = cat_url(cat) %>
    <% button_text = "edit cat" %>
<% else %>
    <% bollocks = cats_url %>
    <% button_text = "new cat" %>
<% end %>

<form action="<%= bollocks %>" method="POST">

    <% if edit %>
        <input type="hidden" name="_method" value="PATCH">
    <% end %>

    <label for="cat_name">Name: </label>
    <input id="cat_name" type="text" name="cat[name]" value="<%= cat.name %>">
    
    <label for="cat_birth_date">Birthday: </label>
    <input id="cat_birth_date" type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">
    
    <label for="cat_color">Color: </label>
    <input id="cat_color" type="text" name="cat[color]"  value="<%= cat.color %>">

    <label for="cat_sex">Sex: </label>
    <select name="cat[sex]" id="cat_sex">
        <option disabled <%= cat.sex ? "" : "selected" %>>--</option>
        <option value="M" <%= cat.sex == "M" ? "selected" : "" %>>M</option>
        <option value="F" <%= cat.sex == "F" ? "selected" : "" %>>F</option>
    </select>

    <label for="cat_description">Description: </label>
    <textarea name="cat[description]" id="cat_description" cols="2" rows="2"><%= cat.description %></textarea>

    <input type="submit" value="<%= button_text %>">
</form>

http_cats/app/views/cats/edit.html.erb
<h1>Edit a cat:</h1>

<%= render "form", cat: @cat, edit: true %>

http_cats/app/views/cats/index.html.erb
<h1>All Cats</h1>

<ul>
<% @cats.each do |cat| %>
   <li> <a href="<%=cat_url(cat)%>"><%= cat.name %></a> </li> 
<% end %>
</ul>

http_cats/app/views/cats/new.html.erb
<h1>Add a cat:</h1>

<%= render "form", cat: @cat, edit: false %>

http_cats/app/views/cats/show.html.erb
<h1><%= @cat.name.capitalize %>'s clubhouse</h1>

<ul>
<li>Color: <%= @cat.color%></li>
<li>Sex: <%= @cat.sex%></li>
<li>Birthday: <%= @cat.birth_date%></li>
<li>Description: <%= @cat.description%></li>
</ul>

http_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HttpCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>